name: CI/CD - Flask App!

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: davmano/flask-app

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 🛠️ Build Docker image
      run: docker build -t $IMAGE_NAME:latest .

    - name: 🧪 Test container
      run: |
        docker run -d -p 5000:5000 --name test-container $IMAGE_NAME:latest
        echo "⏳ Waiting for app to be ready..."
        for i in {1..10}; do
          if curl --fail http://localhost:5000; then
            echo "✅ App is up!"
            break
          fi
          echo "Retrying in 3s..."
          sleep 3
        done
        # Final check
        curl --fail http://localhost:5000 || (echo "❌ App test failed" && docker logs test-container && exit 1)
        docker rm -f test-container

    - name: 📦 Push to Docker Hub
      run: docker push $IMAGE_NAME:latest
    
    - name: Deploy with Helm
      run: |
        helm upgrade --install flask-app ./helm/flask-chart \
        --set image.tag=${{ github.sha }}

